[header]
template   = ${HEADER_TEMPLATE}
title      = INAZUMA11
serial     = BOEJ
maker      = HF
revision   = 0
secure-crc = 0x9277

[rom]
# Do *NOT* change the following line!
storage-type = PROM
fill-tail    = true
fill-with    = 0xFF

[banner]
version   = 1
icon      = ${ICON_PNG}
title     = イナズマイレブン3
subtitle  = せかいへのちょうせん！OG
developer = LEVEL5

[arm9]
static-binary = main.sbin_LZ
definitions   = main_defs.sbin_LZ
overlay-table = main_table.sbin_LZ

[arm7]
static-binary = ${ARM7_STATIC}
definitions   = ${ARM7_DEFINE}